module.exports = [
  {
    id: 1,
    item_name: "Salary",
    amount: 5000,
    date: "2023-07-01",
    from: "Employer",
    category: "Income",
  },
  {
    id: 2,
    item_name: "Rent",
    amount: -1500,
    date: "2023-07-01",
    from: "Landlord",
    category: "Expense",
  },
  {
    id: 3,
    item_name: "Groceries",
    amount: -200,
    date: "2023-07-02",
    from: "Supermarket",
    category: "Expense",
  },
  {
    id: 4,
    item_name: "Dividend",
    amount: 100,
    date: "2023-07-03",
    from: "Investments",
    category: "Income",
  },
  {
    id: 5,
    item_name: "Utilities",
    amount: -100,
    date: "2023-07-03",
    from: "Utility Company",
    category: "Expense",
  },
  {
    id: 6,
    item_name: "Dinner",
    amount: -50,
    date: "2023-07-04",
    from: "Restaurant",
    category: "Expense",
  },
  {
    id: 7,
    item_name: "Bonus",
    amount: 2000,
    date: "2023-07-05",
    from: "Employer",
    category: "Income",
  },
  {
    id: 8,
    item_name: "Movie Tickets",
    amount: -30,
    date: "2023-07-05",
    from: "Cinema",
    category: "Expense",
  },
];
